platform :ios, '6.0'
pod 'Nimbus'
pod 'BlocksKit'
pod 'Overline-BlocksKit'
pod 'FlatUIKit'
pod 'TransitionKit'
pod 'SVProgressHUD'
pod 'RestKit'
pod 'REMenu'
pod 'ActionSheetPicker2', '~> 0.1'
pod 'ODRefreshControl'