platform :ios, '6.0'
pod 'AFNetworking', '~> 1.2'
pod 'Nimbus'
pod 'BlocksKit'
pod 'Overline-BlocksKit'
pod 'FlatUIKit'
pod 'TransitionKit'
pod 'SVProgressHUD'
pod 'RestKit'
pod 'REMenu'
pod 'ActionSheetPicker2', '~> 0.1'
pod 'ODRefreshControl'
pod 'HorizontalPicker'
pod 'SIAlertView'
pod 'GoogleAnalytics-iOS-SDK'
pod 'uservoice-iphone-sdk'
pod 'TestFlightSDK', '~> 1.2.6'
pod 'GCOLaunchImageTransition'
pod 'Appirater'
